const CACHE='gmao-pwa-v004';
self.addEventListener('install',event=>{
  event.waitUntil(
    caches.open(CACHE).then(cache=>
      cache.addAll([
        './',
        './index.html',
        './app.js',
        './manifest.webmanifest'
      ])
    )
  );
});
self.addEventListener('activate',event=>{
  event.waitUntil(
    caches.keys().then(keys=>
      Promise.all(
        keys
          .filter(key=>key!==CACHE)
          .map(key=>caches.delete(key))
      )
    )
  );
});
self.addEventListener('fetch',event=>{
  event.respondWith(
    fetch(event.request)
      .catch(()=>caches.match(event.request))
  );
});
