-- 01_gm_product.sql
-- Source sheet: product_db
-- Column structure is preserved from the uploaded workbook.

CREATE TABLE IF NOT EXISTS gm_product (
  product_uid TEXT NOT NULL,
  glomart_code TEXT NOT NULL,
  gm_category TEXT NOT NULL,
  category_keyword TEXT,
  mall_code TEXT NOT NULL,
  source_mall TEXT,
  source_uid TEXT,
  mall_category TEXT,
  product_id TEXT NOT NULL,
  item_id TEXT,
  vendor_item_id TEXT NOT NULL,
  pi_ii_vi TEXT,
  internal_product_code TEXT,
  product_name TEXT NOT NULL,
  mall_product_name TEXT,
  option_count INTEGER,
  option_json JSONB NOT NULL DEFAULT '{"default_uid":"","option_count":0,"updated_at":null,"options":[]}'::jsonb,
  thumb_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  option_name TEXT,
  option_value TEXT,
  origin_country TEXT,
  storage_type TEXT,
  storage_method TEXT,
  shelf_life_text TEXT,
  seasonal_yn TEXT,
  mall_sale_price INTEGER NOT NULL,
  final_supply_price INTEGER,
  normal_price INTEGER,
  discount_price INTEGER,
  delivery_fee INTEGER,
  delivery_eta_text TEXT,
  delivery_days_range TEXT,
  delivery_type TEXT,
  tax_type TEXT,
  overseas_direct_yn TEXT,
  review_count INTEGER,
  mall_sales_count TEXT,
  certification_no_1 TEXT,
  certification_no_2 TEXT,
  supplier_id TEXT,
  supplier_name_snapshot TEXT,
  business_number_snapshot TEXT,
  online_sales_number_snapshot TEXT,
  ceo_name_snapshot TEXT,
  supplier_mobile_snapshot TEXT,
  supplier_phone_snapshot TEXT,
  supplier_email_snapshot TEXT,
  supplier_address_snapshot TEXT,
  product_url TEXT NOT NULL,
  thumb_origin_url TEXT NOT NULL,
  thumb_file_name TEXT NOT NULL,
  soldout_yn TEXT,
  hit_count INTEGER,
  detail_view_count INTEGER,
  cart_count INTEGER,
  wish_count INTEGER NOT NULL DEFAULT 0,
  order_count INTEGER,
  order_qty_total INTEGER NOT NULL DEFAULT 0,
  product_grade TEXT,
  last_seen_at TIMESTAMP,
  last_cart_at TIMESTAMP,
  last_wish_at TIMESTAMP,
  last_order_at TIMESTAMP,
  expire_at TIMESTAMP,
  registered_our_product_yn TEXT,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  sale_status TEXT,
  collect_status TEXT,
  collect_error TEXT,
  sale_unit_text TEXT,
  unit_price_text TEXT,
  unit_price_value NUMERIC,
  unit_base_qty NUMERIC,
  unit_base_unit TEXT,
  unit_norm_qty NUMERIC,
  unit_norm_unit TEXT,
  unit_norm_price NUMERIC,
  unit_parse_status TEXT,
  unit_sortable_yn TEXT,
  PRIMARY KEY (product_uid)
);

-- Patch: keep original gm_product schema and ensure existing old deployments have mall_code.
-- This does not change expire_at/created_at/updated_at definitions.
ALTER TABLE IF EXISTS gm_product
  ADD COLUMN IF NOT EXISTS mall_code TEXT NOT NULL DEFAULT 'CPKR';


-- Patch: mall sales count is part of base product schema.
ALTER TABLE IF EXISTS gm_product
  ADD COLUMN IF NOT EXISTS mall_sales_count TEXT;
