-- 01_gm_product.sql
-- 개발용 즉시 테스트 스키마. 정식 스타트 전까지는 배포 시 gm_product를 DROP/CREATE 한다.
-- V027: cp_id/cp_code 대신 cp_selected_code/cp_fix_code 적용. cp_match는 T 보호/F 전파 기준.

DROP TABLE IF EXISTS gm_product CASCADE;

CREATE TABLE gm_product (
  product_uid TEXT NOT NULL,
  glomart_code TEXT NOT NULL DEFAULT '',
  gm_category TEXT NOT NULL DEFAULT '',
  category_keyword TEXT,
  keyword TEXT,
  mall_code TEXT NOT NULL,
  source_mall TEXT,
  source_uid TEXT,
  mall_category TEXT,
  mall_category_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  cp_selected_code TEXT,
  cp_fix_code TEXT,
  cp_match TEXT NOT NULL DEFAULT 'F',
  product_id TEXT NOT NULL,
  item_id TEXT,
  vendor_item_id TEXT NOT NULL,
  pi_ii_vi TEXT,
  internal_product_code TEXT,
  product_name TEXT NOT NULL,
  mall_product_name TEXT,
  option_count INTEGER NOT NULL DEFAULT 0,
  option_json JSONB NOT NULL DEFAULT '{"default_uid":"","option_count":0,"updated_at":null,"headers":[],"rows":[]}'::jsonb,
  thumb_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  seasonal_text TEXT,
  mall_sale_price INTEGER NOT NULL DEFAULT 0,
  final_supply_price INTEGER,
  normal_price INTEGER,
  discount_price INTEGER,
  delivery_fee INTEGER,
  delivery_eta_text TEXT,
  delivery_type TEXT,
  tax_type TEXT,
  overseas_direct_yn TEXT NOT NULL DEFAULT 'N',
  review_count INTEGER,
  mall_sales_count TEXT,
  certification_no_1 TEXT,
  certification_no_2 TEXT,
  supplier_id TEXT,
  supplier_name TEXT,
  business_number TEXT,
  online_sales_number TEXT,
  ceo_name TEXT,
  supplier_mobile TEXT,
  supplier_phone TEXT,
  supplier_email TEXT,
  supplier_address TEXT,
  product_url TEXT NOT NULL,
  thumb_origin_url TEXT,
  soldout_yn TEXT NOT NULL DEFAULT 'N',
  hit_count INTEGER NOT NULL DEFAULT 0,
  detail_view_count INTEGER NOT NULL DEFAULT 0,
  cart_count INTEGER NOT NULL DEFAULT 0,
  wish_count INTEGER NOT NULL DEFAULT 0,
  order_count INTEGER NOT NULL DEFAULT 0,
  order_qty_total INTEGER NOT NULL DEFAULT 0,
  product_grade TEXT,
  last_seen_at TIMESTAMP,
  last_cart_at TIMESTAMP,
  last_wish_at TIMESTAMP,
  last_order_at TIMESTAMP,
  registered_our_product_yn TEXT NOT NULL DEFAULT 'N',
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP,
  sale_status TEXT NOT NULL DEFAULT 'active',
  buyable_qty INTEGER,
  min_order_qty INTEGER,
  max_order_qty INTEGER,
  return_available_yn TEXT NOT NULL DEFAULT 'Y',
  exchange_available_yn TEXT NOT NULL DEFAULT 'Y',
  return_policy_text TEXT,
  exchange_policy_text TEXT,
  return_shipping_fee INTEGER NOT NULL DEFAULT 0,
  exchange_shipping_fee INTEGER NOT NULL DEFAULT 0,
  return_period_days INTEGER,
  exchange_period_days INTEGER,
  PRIMARY KEY (product_uid)
);

CREATE INDEX IF NOT EXISTS idx_gm_product_keyword ON gm_product(keyword);
CREATE INDEX IF NOT EXISTS idx_gm_product_mall_code ON gm_product(mall_code);
CREATE INDEX IF NOT EXISTS idx_gm_product_cp_selected_code ON gm_product(cp_selected_code);
CREATE INDEX IF NOT EXISTS idx_gm_product_cp_fix_code ON gm_product(cp_fix_code);
CREATE INDEX IF NOT EXISTS idx_gm_product_cp_match ON gm_product(cp_match);
CREATE INDEX IF NOT EXISTS idx_gm_product_pi_ii_vi ON gm_product(pi_ii_vi);
