-- 03_gm_order.sql
-- Source sheet: 주문서DB_최소구조
-- Column structure is preserved from the uploaded workbook.

CREATE TABLE IF NOT EXISTS gm_order (
  order_no TEXT NOT NULL,
  cafe24_order_no TEXT,
  member_id TEXT,
  guest_key TEXT,
  orderer_name TEXT NOT NULL,
  orderer_phone TEXT,
  orderer_mobile TEXT NOT NULL,
  orderer_email TEXT,
  receiver_name TEXT NOT NULL,
  receiver_phone TEXT,
  receiver_mobile TEXT NOT NULL,
  receiver_safe_phone TEXT,
  receiver_zipcode TEXT NOT NULL,
  receiver_address1 TEXT NOT NULL,
  receiver_address2 TEXT,
  delivery_memo TEXT,
  customs_required_yn TEXT,
  customs_clearance_code TEXT,
  customs_name TEXT,
  customs_mobile TEXT,
  payment_method TEXT NOT NULL,
  payment_method_display TEXT NOT NULL,
  payment_bank_name TEXT,
  payment_account_number TEXT,
  depositor_name TEXT,
  depositor_phone TEXT,
  expected_payment_amount INTEGER NOT NULL,
  actual_payment_amount INTEGER,
  payment_difference_amount INTEGER,
  total_product_price INTEGER NOT NULL,
  total_delivery_fee INTEGER NOT NULL,
  extra_area_delivery_fee INTEGER,
  estimated_customs_fee INTEGER,
  estimated_import_vat INTEGER,
  total_payment_price INTEGER NOT NULL,
  order_status TEXT NOT NULL,
  payment_status TEXT NOT NULL,
  shipping_status TEXT NOT NULL,
  delivered_at TIMESTAMP,
  cs_status TEXT,
  ordered_at TIMESTAMP NOT NULL,
  payment_requested_at TIMESTAMP,
  payment_completed_at TIMESTAMP,
  payment_confirmed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  cancel_status TEXT,
  cancel_requested_at TIMESTAMP,
  cancel_completed_at TIMESTAMP,
  purchase_confirmed_yn TEXT,
  purchase_confirmed_at TIMESTAMP,
  PRIMARY KEY (order_no)
);
