-- GM_PRODUCT_IMAGE_EMBEDDING_V003 / REAL[] COMPATIBILITY
-- Image vectors are stored as 512-dimensional REAL[] in gm_product_image_vector.
-- The previous V002 migration attempted CREATE EXTENSION vector and converted the column
-- to pgvector. The current production DB does not provide that extension, and the active
-- image-vector routes/background worker operate on REAL[] instead.
--
-- This migration intentionally performs no schema conversion. Migration 104 already owns
-- the durable table shape:
--   gm_product_image_vector(product_uid TEXT PRIMARY KEY, vector_image REAL[] NOT NULL)
--
-- Keeping this migration as a successful compatibility marker lets the normal migration
-- runner continue to 110/111 without requiring pgvector.
SELECT 1;
