-- GM_AI_CATEGORY_CONNECT_V010
-- Builder-stage AI category classification cache/history.
-- Additive only: no existing table/data is modified or deleted.

CREATE TABLE IF NOT EXISTS gm_category_keyword_map (
  id BIGSERIAL PRIMARY KEY,

  -- Source / lookup identity
  mall_code TEXT NOT NULL DEFAULT 'CPKR',
  category_keyword TEXT NOT NULL,
  keyword_normalized TEXT NOT NULL,
  context_hash TEXT NOT NULL,

  -- Context shown to the classifier
  sample_products JSONB NOT NULL DEFAULT '[]'::jsonb,
  candidate_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  candidate_round SMALLINT NOT NULL DEFAULT 0,

  -- AI decision and final Glomart category
  ai_target_gm_code TEXT,
  final_gm_code TEXT,
  parent_gm_code TEXT,
  selection_type TEXT NOT NULL DEFAULT 'PENDING',
  ai_confidence NUMERIC(7,6),
  ai_reason TEXT,
  ai_model TEXT,

  -- Per-classification token trace. Monthly totals remain in gm_ai_usage_monthly.
  prompt_tokens INTEGER NOT NULL DEFAULT 0,
  completion_tokens INTEGER NOT NULL DEFAULT 0,
  total_tokens INTEGER NOT NULL DEFAULT 0,

  -- Provenance / review lifecycle
  classification_source TEXT NOT NULL DEFAULT 'AI',
  status TEXT NOT NULL DEFAULT 'PENDING',
  is_current CHAR(1) NOT NULL DEFAULT 'Y',
  supersedes_id BIGINT REFERENCES gm_category_keyword_map(id),
  reviewed_by TEXT,
  review_note TEXT,
  classified_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One active decision for the same mall + normalized keyword + product-context fingerprint.
-- Historical/corrected rows remain because only is_current='Y' participates in this unique index.
CREATE UNIQUE INDEX IF NOT EXISTS uq_gm_category_keyword_map_current
  ON gm_category_keyword_map(mall_code, keyword_normalized, context_hash)
  WHERE is_current='Y';

CREATE INDEX IF NOT EXISTS idx_gm_category_keyword_map_keyword
  ON gm_category_keyword_map(mall_code, keyword_normalized);

CREATE INDEX IF NOT EXISTS idx_gm_category_keyword_map_final_code
  ON gm_category_keyword_map(final_gm_code)
  WHERE is_current='Y';

CREATE INDEX IF NOT EXISTS idx_gm_category_keyword_map_ai_target
  ON gm_category_keyword_map(ai_target_gm_code);

CREATE INDEX IF NOT EXISTS idx_gm_category_keyword_map_status
  ON gm_category_keyword_map(status, is_current, updated_at DESC);

COMMENT ON TABLE gm_category_keyword_map IS
  'AI/category algorithm mapping cache and audit history for unmatched or ambiguous category keywords.';
COMMENT ON COLUMN gm_category_keyword_map.ai_target_gm_code IS
  'gm_code selected by AI: existing leaf code or parent code when a new child must be generated.';
COMMENT ON COLUMN gm_category_keyword_map.final_gm_code IS
  'Final Glomart gm_code actually assigned after existing-leaf selection or child-code generation.';
COMMENT ON COLUMN gm_category_keyword_map.context_hash IS
  'Deterministic server-generated fingerprint of normalized product/category context; not generated by AI.';
COMMENT ON COLUMN gm_category_keyword_map.selection_type IS
  'Decision type such as EXISTING_LEAF, NEW_CHILD, UNCLASSIFIED_CHILD, or PENDING.';
COMMENT ON COLUMN gm_category_keyword_map.classification_source IS
  'Provenance such as AI, ADMIN, or ORIGINAL.';
