-- 18_gm_product_category_operational_metrics.sql
-- Operational cumulative counters on product/category for builder search and dashboard.

ALTER TABLE IF EXISTS gm_product
  ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS search_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wish_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cart_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS order_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sales_qty BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sales_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS purchase_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gross_profit NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS return_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exchange_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_view_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_order_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_sales_qty BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_sales_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_search_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_view_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_order_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_return_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_exchange_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_ad_view_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_ad_order_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS gm_product_archive
  ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS search_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wish_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cart_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS order_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sales_qty BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sales_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS purchase_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gross_profit NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS return_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exchange_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_view_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_order_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_sales_qty BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_sales_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_search_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_view_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_order_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_return_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_exchange_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_ad_view_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_ad_order_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS gm_category
  ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS search_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wish_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cart_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS order_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sales_qty BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sales_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS purchase_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gross_profit NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS return_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exchange_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_view_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_order_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_sales_qty BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ad_sales_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_search_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_view_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_order_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_return_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_exchange_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_ad_view_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_ad_order_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_gm_product_search_count ON gm_product (search_count DESC);
CREATE INDEX IF NOT EXISTS idx_gm_product_sales_amount ON gm_product (sales_amount DESC);
CREATE INDEX IF NOT EXISTS idx_gm_product_ad_view_count ON gm_product (ad_view_count DESC);

CREATE INDEX IF NOT EXISTS idx_gm_category_search_count ON gm_category (search_count DESC);
CREATE INDEX IF NOT EXISTS idx_gm_category_sales_amount ON gm_category (sales_amount DESC);
CREATE INDEX IF NOT EXISTS idx_gm_category_ad_view_count ON gm_category (ad_view_count DESC);
