-- DEPRECATED / INTENTIONALLY NO-OP
--
-- The final three-column gm_keyword_relation schema is created directly by
-- 26_gm_keyword_relation.sql.
--
-- This migration previously transformed/recreated the table and caused the
-- relation table or its stored data to disappear during the schema change.
-- Keep this file as a no-op only when the deployment process cannot delete an
-- already tracked migration file. It must never DROP, ALTER, TRUNCATE, or
-- recreate gm_keyword_relation.
