'use strict';
// GM_PRODUCT_GLOMART_CODE_V010_SHARED_SERVER_MATCHER
const express=require('express');
const router=express.Router();
const {dbFrom,ok,fail}=require('./core');
const {
  MULTI_MAX, raw, loadMaps, loadHistory, classify, invalidateContext
}=require('../../services/glomart_code');

const APPLY_BATCH=250;
function statNorm(v){return String(v==null?'':v).normalize('NFKC').trim().toLowerCase().replace(/\s+/g,'');}
async function status(db){const r=await db.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE COALESCE(glomart_code,'')<>'')::int filled,COUNT(*) FILTER(WHERE COALESCE(glomart_code,'')='')::int empty,COUNT(*) FILTER(WHERE POSITION('|' IN COALESCE(glomart_code,''))>0)::int multi FROM gm_product`);return {...(r.rows[0]||{})};}
async function loadProducts(db,limit){const params=[];let lim='';if(limit){params.push(limit);lim=' LIMIT $1';}const r=await db.query(`SELECT product_uid,glomart_code,cp_selected_code,cp_fix_code,category_code,category_keyword,keyword,product_name,mall_code,mall_category FROM gm_product WHERE COALESCE(glomart_code,'')='' ORDER BY product_uid${lim}`,params);return r.rows;}
function summarize(items){const s={matched:0,matched_single:0,matched_multi:0,unmatched:0,ambiguous:0,by:{}};for(const x of items){s.by[x.match_by]=(s.by[x.match_by]||0)+1;if(x.gm_code){s.matched++;if(String(x.gm_code).includes('|'))s.matched_multi++;else s.matched_single++;}else{s.unmatched++;if(String(x.match_by).startsWith('AMBIGUOUS_'))s.ambiguous++;}}return s;}

async function loadCleanupCandidates(db,limit){
  const r=await db.query(`SELECT product_uid,product_name,category_keyword,keyword FROM gm_product WHERE COALESCE(glomart_code,'')='' AND (COALESCE(category_keyword,'')<>'' OR COALESCE(keyword,'')<>'') ORDER BY product_uid`);
  const grouped=new Map();
  function add(field,value,row){const v=raw(value);if(!v)return;let x=grouped.get(v);if(!x){x={value:v,fields:new Set(),product_uids:new Set(),samples:[]};grouped.set(v,x);}x.fields.add(field);x.product_uids.add(raw(row.product_uid));if(x.samples.length<3&&row.product_name)x.samples.push(raw(row.product_name));}
  for(const row of r.rows){add('category_keyword',row.category_keyword,row);add('keyword',row.keyword,row);}
  const norms=[...new Set([...grouped.values()].map(x=>statNorm(x.value)).filter(Boolean))];
  const stats=new Map();
  if(norms.length){
    const sr=await db.query(`SELECT keyword_normalized,COALESCE(SUM(search_count),0)::int AS search_count,MIN(first_search_at) AS first_search_at,MAX(last_search_at) AS last_search_at FROM gm_search_keyword_stat WHERE keyword_normalized=ANY($1::text[]) GROUP BY keyword_normalized`,[norms]);
    for(const row of sr.rows)stats.set(raw(row.keyword_normalized),row);
  }
  const out=[];
  for(const x of grouped.values()){
    const st=stats.get(statNorm(x.value))||{};const sc=Number(st.search_count||0);if(sc>1)continue;
    out.push({value:x.value,fields:[...x.fields].sort(),product_count:x.product_uids.size,search_count:sc,first_search_at:st.first_search_at||null,last_search_at:st.last_search_at||null,samples:x.samples});
  }
  out.sort((a,b)=>a.search_count-b.search_count||b.product_count-a.product_count||a.value.localeCompare(b.value,'ko'));
  return out.slice(0,Math.max(1,Math.min(Number(limit||500),2000)));
}

router.get('/api/gm/builder/product-gm-code/status',async(req,res)=>{const db=dbFrom(req);if(!db)return fail(res,500,'DB_NOT_READY');try{ok(res,{action:'product-gm-code.status',...(await status(db))});}catch(e){fail(res,500,'PRODUCT_GM_CODE_STATUS_FAILED',{detail:String(e&&e.message||e)});}});
router.get('/api/gm/builder/product-gm-code/preview',async(req,res)=>{const db=dbFrom(req);if(!db)return fail(res,500,'DB_NOT_READY');try{const limit=Math.min(Math.max(Number(req.query.limit||300),1),2000);const maps=await loadMaps(db),history=await loadHistory(db,maps),products=await loadProducts(db,limit);const items=products.map(p=>({product_uid:p.product_uid,product_name:p.product_name,mall_code:p.mall_code,mall_category:p.mall_category,cp_selected_code:p.cp_selected_code,cp_fix_code:p.cp_fix_code,category_code:p.category_code,category_keyword:p.category_keyword,keyword:p.keyword,...classify(p,maps,history)}));ok(res,{action:'product-gm-code.preview',limit,category_count:maps.category_count,history:{learned:history.learned,skipped_multi:history.skippedMulti,skipped_unknown:history.skippedUnknown},summary:summarize(items),items});}catch(e){fail(res,500,'PRODUCT_GM_CODE_PREVIEW_FAILED',{detail:String(e&&e.message||e)});}});
router.get('/api/gm/builder/product-gm-code/analyze',async(req,res)=>{const db=dbFrom(req);if(!db)return fail(res,500,'DB_NOT_READY');try{const maps=await loadMaps(db),history=await loadHistory(db,maps),products=await loadProducts(db,0);const classified=products.map(p=>classify(p,maps,history));ok(res,{action:'product-gm-code.analyze',category_count:maps.category_count,history:{learned:history.learned,skipped_multi:history.skippedMulti,skipped_unknown:history.skippedUnknown},scanned:products.length,summary:summarize(classified),multi_max:MULTI_MAX});}catch(e){fail(res,500,'PRODUCT_GM_CODE_ANALYZE_FAILED',{detail:String(e&&e.message||e)});}});
router.post('/api/gm/builder/product-gm-code/apply',async(req,res)=>{const db=dbFrom(req);if(!db)return fail(res,500,'DB_NOT_READY');if(String(req.query.confirm||req.body&&req.body.confirm||'').toUpperCase()!=='YES')return fail(res,400,'CONFIRM_REQUIRED',{hint:'confirm=YES'});let client=null,release=false;try{const maps=await loadMaps(db),history=await loadHistory(db,maps),products=await loadProducts(db,0);const matched=[],classified=[];for(const p of products){const c=classify(p,maps,history);classified.push(c);if(c.gm_code)matched.push({product_uid:p.product_uid,...c});}client=typeof db.connect==='function'?await db.connect():db;release=client!==db&&typeof client.release==='function';await client.query('BEGIN');let updated=0;for(let i=0;i<matched.length;i+=APPLY_BATCH){const batch=matched.slice(i,i+APPLY_BATCH),vals=[],rows=[];let n=1;for(const x of batch){rows.push(`($${n++}::text,$${n++}::text)`);vals.push(x.product_uid,x.gm_code);}const q=await client.query(`UPDATE gm_product p SET glomart_code=v.gm_code,updated_at=COALESCE(p.updated_at,NOW()) FROM (VALUES ${rows.join(',')}) AS v(product_uid,gm_code) WHERE p.product_uid=v.product_uid AND COALESCE(p.glomart_code,'')=''`,vals);updated+=q.rowCount||0;}await client.query('COMMIT');invalidateContext(db);const summary=summarize(classified);console.log(`[GM_PRODUCT_GLOMART_CODE_V010] apply scanned=${products.length} matched=${summary.matched} single=${summary.matched_single} multi=${summary.matched_multi} ambiguous=${summary.ambiguous} unmatched=${summary.unmatched} updated=${updated} by=${JSON.stringify(summary.by)}`);ok(res,{action:'product-gm-code.apply',category_count:maps.category_count,history:{learned:history.learned},scanned:products.length,updated,summary});}catch(e){try{if(client)await client.query('ROLLBACK');}catch(_){}fail(res,500,'PRODUCT_GM_CODE_APPLY_FAILED',{detail:String(e&&e.message||e)});}finally{if(release)client.release();}});

router.get('/api/gm/builder/product-gm-code/cleanup-candidates',async(req,res)=>{const db=dbFrom(req);if(!db)return fail(res,500,'DB_NOT_READY');try{const limit=Math.min(Math.max(Number(req.query.limit||500),1),2000);const items=await loadCleanupCandidates(db,limit);ok(res,{action:'product-gm-code.cleanup-candidates',items,count:items.length,rule:'unclassified + search_count<=1; manual selection only'});}catch(e){fail(res,500,'PRODUCT_GM_CODE_CLEANUP_CANDIDATES_FAILED',{detail:String(e&&e.message||e)});}});
router.post('/api/gm/builder/product-gm-code/cleanup-delete',async(req,res)=>{const db=dbFrom(req);if(!db)return fail(res,500,'DB_NOT_READY');const selected=Array.isArray(req.body&&req.body.items)?req.body.items:[];if(!selected.length)return fail(res,400,'NO_SELECTION');let updated=0;const result=[];try{for(const item of selected){const value=raw(item&&item.value);if(!value)continue;const fields=Array.isArray(item&&item.fields)?item.fields:[];let rowCount=0;if(fields.includes('category_keyword')){const q=await db.query(`UPDATE gm_product SET category_keyword=NULL,updated_at=now() WHERE COALESCE(glomart_code,'')='' AND category_keyword=$1`,[value]);rowCount+=q.rowCount||0;}if(fields.includes('keyword')){const q=await db.query(`UPDATE gm_product SET keyword=NULL,updated_at=now() WHERE COALESCE(glomart_code,'')='' AND keyword=$1`,[value]);rowCount+=q.rowCount||0;}updated+=rowCount;result.push({value,fields,row_count:rowCount});}invalidateContext(db);console.log(`[GM_PRODUCT_GLOMART_CODE_V010] cleanup selected=${selected.length} field_updates=${updated}`);ok(res,{action:'product-gm-code.cleanup-delete',selected:selected.length,field_updates:updated,result});}catch(e){fail(res,500,'PRODUCT_GM_CODE_CLEANUP_DELETE_FAILED',{detail:String(e&&e.message||e)});}});

function csvCell(v){if(v===null||v===undefined)return '';const x=String(v);return /[",\r\n]/.test(x)?'"'+x.replace(/"/g,'""')+'"':x;}
router.get('/api/gm/builder/product-gm-code/unmatched.csv',async(req,res)=>{const db=dbFrom(req);if(!db)return fail(res,500,'DB_NOT_READY');try{const maps=await loadMaps(db),history=await loadHistory(db,maps);const cols=['product_uid','mall_code','product_name','cp_selected_code','cp_fix_code','mall_category','category_code','category_keyword','keyword','match_by','source_field','source_value','candidate_count','history_count','resolved_gm_code','category_name'];res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="gm_product_glomart_code_unmatched_${Date.now()}.csv"`);res.setHeader('Cache-Control','no-store, no-cache, must-revalidate');res.setHeader('X-Content-Type-Options','nosniff');const writeChunk=async chunk=>{if(res.write(chunk))return;if(res.destroyed)throw new Error('client disconnected');await new Promise(resolve=>res.once('drain',resolve));};await writeChunk('\ufeff'+cols.join(',')+'\n');const pageSize=1000;let lastUid='',sent=0;while(true){const r=await db.query(`SELECT product_uid,glomart_code,cp_selected_code,cp_fix_code,mall_category,category_code,category_keyword,keyword,product_name,mall_code FROM gm_product WHERE COALESCE(glomart_code,'')='' AND product_uid>$1 ORDER BY product_uid ASC LIMIT $2`,[lastUid,pageSize]);if(!r.rows.length)break;for(const row of r.rows){const c=classify(row,maps,history);if(c.gm_code)continue;const out={...row,...c,resolved_gm_code:c.gm_code};await writeChunk(cols.map(k=>csvCell(out[k])).join(',')+'\n');sent++;}lastUid=String(r.rows[r.rows.length-1].product_uid||'');if(r.rows.length<pageSize)break;}console.log(`[GM_PRODUCT_GLOMART_CODE_V010] unmatched export sent=${sent}`);res.end();}catch(e){if(!res.headersSent)return fail(res,500,'PRODUCT_GM_CODE_UNMATCHED_EXPORT_FAILED',{detail:String(e&&e.message||e)});try{res.end();}catch(_){}}});

module.exports=router;
